CinemaTic.Web/Areas/Customer/Controllers/MoviesController.cs
using CinemaTic.Core.Contracts;
using CinemaTic.Extensions.ModelBinders;
using CinemaTic.Web.Areas.Customer.Controllers.BaseControllers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CinemaTic.Web.Areas.Customer.Controllers
{
    public class MoviesController : CustomerController
    {
        private readonly IMoviesService _moviesService;
        private readonly ICinemasService _cinemasService;
        private readonly ICustomersService _customersService;

        public MoviesController(IMoviesService moviesService, ICinemasService cinemasService, ICustomersService customersService)
        {
            _moviesService = moviesService;
            _cinemasService = cinemasService;
            _customersService = customersService;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            return View(await _moviesService.GetDetailsViewModelAsync(id, User.Identity.Name));
        }
        [HttpGet]
        public async Task<IActionResult> GetMoviesByDate([ModelBinder(typeof(IntegerModelBinder))] int cinemaId, [ModelBinder(typeof(DateModelBinder))] DateTime date)
        {
            if (!await _cinemasService.ExistsByIdAsync(cinemaId))
            {
                return NotFound();
            }
            return PartialView("_MoviesByDatePartial", await _customersService.GetMoviesByDateAsync(cinemaId, date));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetRating(int? movieId, int? rating)
        {
            if (movieId == null)
            {
                return NotFound();
            }
            if (!await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }
            if (rating == 0 || rating == null)
            {
                return RedirectToAction(nameof(Details), new { id = movieId });
            }

            await _customersService.SetRatingToMovieAsync(movieId, rating.Value, User.Identity.Name);

            return RedirectToAction(nameof(Details), new { id = movieId });
        }
    }
}

CinemaTic.Web/Areas/Customer/Controllers/TicketsController.cs
using CinemaTic.Core.Contracts;
using CinemaTic.Extensions.ModelBinders;
using CinemaTic.ViewModels.Sectors;
using CinemaTic.Web.Areas.Customer.Controllers.BaseControllers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace CinemaTic.Web.Areas.Customer.Controllers
{
    public class TicketsController : CustomerController
    {
        private readonly ICustomersService _customersService;
        private readonly ICinemasService _cinemasService;
        private readonly IMoviesService _moviesService;
        private readonly ISectorsService _sectorsService;

        public TicketsController(ICustomersService customersService, ICinemasService cinemasService, IMoviesService moviesService, ISectorsService sectorsService)
        {
            _customersService = customersService;
            _cinemasService = cinemasService;
            _moviesService = moviesService;
            _sectorsService = sectorsService;
        }

        public async Task<IActionResult> QueryTickets(string searchText, int? pageNumber)
        {
            var tickets = await _customersService.QueryTicketsAsync(User.Identity.Name, searchText, pageNumber);
            return PartialView("_TicketsPartial", tickets);
        }

        public async Task<IActionResult> BuyTicket(int cinemaId, int movieId, [ModelBinder(typeof(DateModelBinder))] DateTime forDate)
        {
            if (!await _cinemasService.ExistsByIdAsync(cinemaId))
            {
                return NotFound();
            }
            if (!await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }
            if (!await _customersService.CustomerHasCinemaAsync(cinemaId, User.Identity.Name))
            {
                TempData["ErrorMessage"] = "You must add this cinema to favorites in order to buy tickets!";
                return Forbid();
            }
            return View(await _customersService.GetBuyTicketViewModelAsync(cinemaId, movieId, forDate));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuyTicket(int sectorId, int movieId, SectorDetailsViewModel viewModel, DateTime forDate)
        {
            if (!await _sectorsService.ExistsByIdAsync(sectorId))
            {
                return NotFound();
            }
            if (!await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }
            await _customersService.BuyTicketAsync(sectorId, movieId, User.Identity.Name, viewModel, forDate);
            return Redirect(Url.RouteUrl(new { controller = "Dashboard", action = "Index"}) + "#tickets");
        }
    }
}

CinemaTic.Web/Areas/Owner/Controllers/MoviesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CinemaTic.Core.Contracts;
using CinemaTic.ViewModels.Movies;
using CinemaTic.Extensions.ModelBinders;
using System.Linq;
using CinemaTic.Web.Areas.Owner.Controllers.BaseControllers;

namespace CinemaTic.Web.Areas.Owner.Controllers
{
    public class MoviesController : OwnerController
    {
        private readonly IMoviesService _moviesService;
        private readonly ICinemasService _cinemasService;

        public MoviesController(IMoviesService moviesService, ICinemasService cinemasService)
        {
            _moviesService = moviesService;
            _cinemasService = cinemasService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _moviesService.GetFilterViewModelAsync());
        }
        public async Task<IActionResult> QueryMovies(string searchText, string filterValue, string sortBy, [ModelBinder(typeof(IntegerModelBinder))] int? pageNumber)
        {
            var movies = await _moviesService.QueryMoviesAsync(searchText, filterValue, sortBy, pageNumber ?? 1);
            return PartialView("_MoviesPartial", movies);
        }
        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            var viewModel = await _moviesService.GetDetailsViewModelAsync(id, User.Identity.Name);
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // GET: Movies/Create
        public async Task<IActionResult> Add()
        {
            return View(await _moviesService.GetCreateViewModelAsync());
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CreateMovieViewModel movieVM)
        {
            if (!movieVM.ActorsDropdown.Where(i => i.IsChecked).Any())
            {
                ModelState.AddModelError("ActorsDropdown", "Select at least 1 actor");
            }
            if (ModelState.IsValid)
            {
                await _moviesService.CreateMovieAsync(movieVM, User.Identity.Name);
                return RedirectToAction(nameof(Index));
            }
            return View(movieVM);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit([ModelBinder(typeof(IntegerModelBinder))] int id)
        {
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            var viewModel = await _moviesService.GetEditViewModelAsync(id);
            if (viewModel == null)
            {
                return NotFound();
            }

            return PartialView("_EditMoviePartial", viewModel);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] EditMovieViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _moviesService.EditMovieAsync(viewModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    bool movieExists = await _moviesService.ExistsByIdAsync(viewModel.Id);
                    if (!movieExists)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = viewModel.Id });
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete([ModelBinder(typeof(IntegerModelBinder))] int id)
        {
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }

            var viewModel = await _moviesService.GetDeleteViewModelAsync(id);
            return PartialView("_DeleteMoviePartial", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            await _moviesService.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMovieToCinemas(MovieDetailsViewModel viewModel)
        {
            if (!await _moviesService.ExistsByIdAsync(viewModel.Id))
            {
                return NotFound();
            }
            await _moviesService.AddMovieToCinemasAsync(viewModel);
            return RedirectToAction(nameof(Details), new { id = viewModel.Id });
        }
        [HttpGet]
        public async Task<IActionResult> SetMovieSchedule(int? cinemaId, int? movieId)
        {
            if (!await _cinemasService.ExistsByIdAsync(cinemaId) || !await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }

            var viewModel = await _moviesService.GetSetMovieScheduleViewModelAsync(cinemaId, movieId);
            if (viewModel == null)
            {
                return NotFound();
            }
            return PartialView("_SetMovieSchedulePartial", viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> SetMovieSchedule(SetMovieScheduleViewModel viewModel)
        {
            if (!await _cinemasService.ExistsByIdAsync(viewModel.CinemaId) || !await _moviesService.ExistsByIdAsync(viewModel.MovieId))
            {
                return NotFound();
            }

            await _moviesService.SetMovieScheduleAsync(viewModel);
            return RedirectToAction(nameof(Details), new { id = viewModel.MovieId });
        }
        [HttpGet]
        public async Task<IActionResult> EditCinemaMovieData(int? cinemaId, int? movieId)
        {
            if (!await _cinemasService.ExistsByIdAsync(cinemaId) || !await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }

            var viewModel = await _moviesService.GetEditCinemaMovieDataViewModelAsync(cinemaId, movieId);
            if (viewModel == null)
            {
                return NotFound();
            }
            return PartialView("_EditCinemaMovieDataPartial", viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditCinemaMovieData(EditCinemaMovieDataViewModel viewModel)
        {
            if (!await _cinemasService.ExistsByIdAsync(viewModel.CinemaId) || !await _moviesService.ExistsByIdAsync(viewModel.MovieId))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _moviesService.EditCinemaMovieDataAsync(viewModel);
            }
            return RedirectToAction(nameof(Details), new { id = viewModel.MovieId });
        }
        public async Task<IActionResult> GetCinemasContainingMovie([ModelBinder(typeof(IntegerModelBinder))] int movieId, string sortBy, [ModelBinder(typeof(IntegerModelBinder))] int? pageNumber)
        {
            if (!await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }
            var viewModel = await _cinemasService.QueryCinemasContainingMovieAsync(movieId, User.Identity.Name, sortBy, pageNumber);
            if (viewModel == null)
            {
                return NotFound();
            }
            return PartialView("_CinemasPartial", viewModel);
        }
    }
}

CinemaTic.Web/Areas/Customer/Views/Movies/Details.cshtml
@model CinemaTic.ViewModels.Movies.MovieDetailsViewModel
@{
    ViewData["Title"] = $"Movie - {Model.Title}";
}

<link href="~/css/cinemas.css" rel="stylesheet" />
<link href="~/css/modal.css" rel="stylesheet" />
<div class="main-cinema-container text-white" style="padding-top: 15vh;">
    <div class="mt-3">
        <section id="trailer" class="dark noBg summary">
            <div class="container-fluid">
                <div class="row mb-5">
                    <div class="col-xs-12 d-flex justify-content-between align-items-center">
                        <h3>@Model.Title</h3>
                        <div class="d-flex gap-1 justify-content-between" style="flex-basis: 35%;">
                            <div class="movie-rating-container">
                                <span>CinemaTic user rating</span>
                                <div class="rating-box d-flex gap-1 mt-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="average" viewBox="0 0 24 24" fill="currentColor" role="presentation">
                                        <path d="M12 17.27l4.15 2.51c.76.46 1.69-.22 1.49-1.08l-1.1-4.72 3.67-3.18c.67-.58.31-1.68-.57-1.75l-4.83-.41-1.89-4.46c-.34-.81-1.5-.81-1.84 0L9.19 8.63l-4.83.41c-.88.07-1.24 1.17-.57 1.75l3.67 3.18-1.1 4.72c-.2.86.73 1.54 1.49 1.08l4.15-2.5z" style=""></path>
                                    </svg>
                                    <div class="rating-number-box">
                                        <span>@string.Format($"{Model.AverageRating:f1} / 10.0") (@Model.RatingCount @string.Format($"{(Model.RatingCount == 1 ? "vote" : "votes")}"))</span>
                                    </div>
                                </div>
                            </div>
                            <div class="movie-rating-container">
                                <span>Your rating</span>
                                <div class="rating-box d-flex gap-1 mt-1">
                                    @if (Model.CurrentUserRating == null)
                                    {
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="personal not-rated open-popup-btn" viewBox="0 0 24 24" fill="currentColor" role="presentation"><path fill="none" d="M0 0h24v24H0V0z"></path><path d="M19.65 9.04l-4.84-.42-1.89-4.45c-.34-.81-1.5-.81-1.84 0L9.19 8.63l-4.83.41c-.88.07-1.24 1.17-.57 1.75l3.67 3.18-1.1 4.72c-.2.86.73 1.54 1.49 1.08l4.15-2.5 4.15 2.51c.76.46 1.69-.22 1.49-1.08l-1.1-4.73 3.67-3.18c.67-.58.32-1.68-.56-1.75zM12 15.4l-3.76 2.27 1-4.28-3.32-2.88 4.38-.38L12 6.1l1.71 4.04 4.38.38-3.32 2.88 1 4.28L12 15.4z"></path></svg>
                                    }
                                    else
                                    {
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="personal open-popup-btn" viewBox="0 0 24 24" fill="currentColor" role="presentation">
                                            <path d="M12 17.27l4.15 2.51c.76.46 1.69-.22 1.49-1.08l-1.1-4.72 3.67-3.18c.67-.58.31-1.68-.57-1.75l-4.83-.41-1.89-4.46c-.34-.81-1.5-.81-1.84 0L9.19 8.63l-4.83.41c-.88.07-1.24 1.17-.57 1.75l3.67 3.18-1.1 4.72c-.2.86.73 1.54 1.49 1.08l4.15-2.5z" style=""></path>
                                        </svg>
                                    }
                                    <div class="rating-number-box d-flex align-items-center">
                                        @if (Model.CurrentUserRating == null)
                                        {
                                            <h6>Rate</h6>
                                        }
                                        else
                                        {
                                            <span>@Model.CurrentUserRating.Value.ToString("f1") / 10.0</span>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="movie-trailer">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="trailer-container">
                                <div class="video-holder">
                                    <iframe id="trailer" src="https://www.youtube-nocookie.com/embed/@Model.TrailerId?hd=1&amp;wmode=opaque&amp;controls=1&amp;showinfo=0&amp;autoplay=1&amp;autoplay=1" aria-label="Trailer of @Model.Title" allowfullscreen="true"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="pt-5">
            <div class="container-fluid">
                <div class="row">
                    <h5>More information about</h5>
                </div>
                <div class="row pt-3">
                    <div class="col-md-8 col-sm-6 col-xs-12">
                        <div class="row d-flex">
                            <div class="col-sm-5">
                                <h6>Running time:</h6>
                                <p>@Model.RunningTime minutes</p>
                            </div>
                            <div class="col-sm-4">
                                <h6>Average rating:</h6>
                                <p>@Model.AverageRating.ToString("f1") / 10.0 (@Model.RatingCount votes)</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <p class="movie-description">@Model.Description</p>
                            </div>
                        </div>
                        <div class="production-info">
                            <div class="production-info-box">
                                <h6>Genre:</h6>
                                <span class="director">@Model.Genre</span>
                            </div>
                            <div class="production-info-box">
                                <h6>Cast:</h6>
                                <span class="actors">@string.Join(", ", @Model.Actors)</span>
                            </div>
                            <div class="production-info-box">
                                <h6>Director:</h6>
                                <span class="director">@Model.Director</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-sm-offset-0 col-xs-6 col-xs-offset-3">
                        <img src="~/client-images/Movies/@Model.ImageUrl" alt="@Model.Title" />
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
<div class="rating-container d-flex justify-content-center align-items-center">
    <div id="modal" style="top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);" role="dialog" aria-modal="true" aria-labelledby="add-review-header" class="edit-modal">
        <button class="close-btn" aria-label="close" title="Close">x</button>
        <div id="ud-form-container">
            <span class="average">RATE THIS</span>
            <span>@Model.Title</span>
            <form class="d-flex justify-content-center mb-5" id="review-form" asp-area="Customer" asp-controller="Movies" asp-action="SetRating" method="post">
                <div class="fieldset">
                    <div class="rate mb-4">
                        @for (int i = 0; i < 10; i++)
                        {
                            <label class="modal-star-container" id="@i" for="rating-@i">
                                <input type="radio" id="rating-@i" name="rating" value="@(i+1)" />
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" class="rate" viewBox="0 0 24 24" fill="currentColor" role="presentation"><path fill="none" d="M0 0h24v24H0V0z"></path><path d="M19.65 9.04l-4.84-.42-1.89-4.45c-.34-.81-1.5-.81-1.84 0L9.19 8.63l-4.83.41c-.88.07-1.24 1.17-.57 1.75l3.67 3.18-1.1 4.72c-.2.86.73 1.54 1.49 1.08l4.15-2.5 4.15 2.51c.76.46 1.69-.22 1.49-1.08l-1.1-4.73 3.67-3.18c.67-.58.32-1.68-.56-1.75zM12 15.4l-3.76 2.27 1-4.28-3.32-2.88 4.38-.38L12 6.1l1.71 4.04 4.38.38-3.32 2.88 1 4.28L12 15.4z"></path></svg>
                            </label>

                        }
                    </div>
                    <input asp-area="Customer" asp-controller="Movies" asp-action="SetRating" asp-route-movieId="@Model.Id" method="post" id="submit-review-btn" class="w-100 rate-button" value="@(Model.CurrentUserRating == null ? "Rate" : "Change rating")" type="submit" />
                </div>
            </form>
        </div>
    </div>
    <div class="modal-overlay"></div>
</div>
<script src="~/js/modal.js"></script>
<script>
    document.getElementsByClassName('app-container')[0].classList.add("h-100");
    document.getElementsByClassName('app-container')[0].classList.add("d-flex");
    document.querySelectorAll('.modal-star-container').forEach(i => {
        var containers = document.querySelectorAll('.modal-star-container');
        let index = Number(i.id);
        i.addEventListener('mouseover', function () {
            fillStars(containers, index);
        });
        i.addEventListener('click', function () {
            fillStars(containers, index);
            currentStars = Number(i.id);
        });
    });
</script>

CinemaTic.Web/Areas/Customer/Views/Movies/_MoviesByDatePartial.cshtml
@model IEnumerable<CinemaTic.ViewModels.Movies.CinemaMovieViewModel>

@foreach (var movie in Model)
{
    <div class="movie d-flex gap-5">
        <div class="movie-poster open-popup-btn position-relative" id="@movie.TrailerId">
            <img src="~/client-images/Movies/@movie.ImageUrl" />
            @if (string.IsNullOrEmpty(movie.TrailerId) == false)
            {
                <i class="fa-regular fa-circle-play trailer-play-button open-popup-btn" id="@movie.TrailerId"></i>
                <div class="movie-poster-overlay"></div>
            }
        </div>
        <div class="movie-info d-flex justify-content-start align-items-start flex-column gap-2">
            <h5><a asp-area="Customer" asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id">@movie.Name</a></h5>
            <div class="d-flex genre-time flex-column">
                <span>@movie.Genre</span>
                <span>@movie.RunningTime minutes</span>
            </div>
            <div class="d-flex flex-wrap gap-2">
                @foreach (var time in movie.Schedule)
                {
                    <form>
                        <a class="time-button" asp-area="Customer" asp-controller="Tickets" asp-action="BuyTicket" asp-route-cinemaId="@movie.CinemaId" asp-route-movieId="@movie.Id" asp-route-forDate="@time">@time.ToString("hh:mm tt")</a>
                    </form>
                }
            </div>
        </div>
    </div>
}
<script>
    openButtons = document.querySelectorAll('.open-popup-btn');
    modal = document.getElementById('modal');
    modalOverlay = document.querySelector('.modal-overlay');
    openButtons.forEach(i => i.addEventListener('click', openModal));

    document.querySelectorAll('.movie-poster, .trailer-play-button').forEach(i => i.addEventListener("click", function () {
        document.getElementById('youtube-container').setAttribute('src', `https://www.youtube-nocookie.com/embed/${i.id}?hd=1&amp;wmode=opaque&amp;controls=1&amp;showinfo=0&amp;autoplay=1&amp;autoplay=1`);
    }));
    document.querySelectorAll('.close-btn, .modal-overlay').forEach(i => i.addEventListener("click", function () {
        document.getElementById('youtube-container').setAttribute('src', ``);
    }));
</script>