CinemaTic.Web/Areas/Admin/Controllers/UsersController.cs
using CinemaTic.Core.Contracts;
using CinemaTic.ViewModels.Admin;
using CinemaTic.Web.Areas.Admin.Controllers.BaseControllers;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CinemaTic.Web.Areas.Admin.Controllers
{
    public class UsersController : AdminController
    {
        private readonly IAdminService _adminService;

        public UsersController(IAdminService adminService)
        {
            _adminService = adminService;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public async Task<IActionResult> User(string id, int? actionPageNumber)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _adminService.GetUserDetailsViewModelByIdAsync(id, actionPageNumber);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        public async Task<IActionResult> QueryUsers(string searchText, string filterValue, string sortBy, int? pageNumber)
        {
            var users = await _adminService.QueryUsersAsync(searchText, filterValue, sortBy, pageNumber);
            return PartialView("_UsersPartial", users);
        }
        public async Task<IActionResult> PromoteToOwner(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!await _adminService.UserExistsAsync(id))
            {
                return NotFound();
            }
            var userViewModel = await _adminService.GetAdminUserCRUDPartialAsync(id);
            if (userViewModel == null)
            {
                return NotFound();
            }
            return PartialView("_PromoteToOwnerPartial", userViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PromoteToOwner([FromForm] AdminUserCRUDViewModel viewModel, string id)
        {
            if (!await _adminService.UserExistsAsync(id))
            {
                return NotFound();
            }
            await _adminService.PromoteUserAsync(id);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> DemoteUser(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!await _adminService.UserExistsAsync(id))
            {
                return NotFound();
            }
            var userViewModel = await _adminService.GetAdminUserCRUDPartialAsync(id);
            if (userViewModel == null)
            {
                return NotFound();
            }
            return PartialView("_DemoteUserPartial", userViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DemoteUser([FromForm] AdminUserCRUDViewModel viewModel, string id)
        {
            if (!await _adminService.UserExistsAsync(id))
            {
                return NotFound();
            }
            await _adminService.DemoteUserAsync(id);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> DeleteUserAccount(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!await _adminService.UserExistsAsync(id))
            {
                return NotFound();
            }
            var userViewModel = await _adminService.GetAdminUserCRUDPartialAsync(id);
            if (userViewModel == null)
            {
                return NotFound();
            }
            return PartialView("_DeleteUserAccountPartial", userViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUserAccount([FromForm] AdminUserCRUDViewModel viewModel, string id)
        {
            if (!await _adminService.UserExistsAsync(id))
            {
                return NotFound();
            }
            await _adminService.DeleteAccountAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

CinemaTic.Web/Areas/Customer/Controllers/CinemasController.cs
using CinemaTic.Core.Contracts;
using CinemaTic.Extensions;
using CinemaTic.Extensions.ModelBinders;
using CinemaTic.ViewModels.Customers;
using CinemaTic.Web.Areas.Customer.Controllers.BaseControllers;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CinemaTic.Web.Areas.Customer.Controllers
{
    public class CinemasController : CustomerController
    {
        private readonly ICustomersService _customersService;
        private readonly ICinemasService _cinemasService;

        public CinemasController(ICustomersService customersService, ICinemasService cinemasService)
        {
            _customersService = customersService;
            _cinemasService = cinemasService;
        }

        public async Task<IActionResult> QueryCinemas(bool? all, string searchText, int? pageNumber)
        {
            var cinemas = await _customersService.QueryCinemasAsync(all,searchText, pageNumber, User.Identity.Name);
            return PartialView("_CinemasPartial", cinemas);
        }
        public async Task<IActionResult> Cinema([ModelBinder(typeof(IntegerModelBinder))] int id)
        {
            if (!await _cinemasService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            return View(await _customersService.PrepareCinemaViewModelAsync(User.Identity.Name, id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCinemaToFavorites(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!await _cinemasService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            await _customersService.AddCinemaToFavoritesAsync(id, User.Identity.Name);
            return Ok();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveCinemaFromFavorites(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!await _cinemasService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            await _customersService.RemoveCinemaFromFavoritesAsync(id, User.Identity.Name);
            return Ok();
        }
    }
}

CinemaTic.Web/Areas/Owner/Controllers/MoviesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CinemaTic.Core.Contracts;
using CinemaTic.ViewModels.Movies;
using CinemaTic.Extensions.ModelBinders;
using System.Linq;
using CinemaTic.Web.Areas.Owner.Controllers.BaseControllers;

namespace CinemaTic.Web.Areas.Owner.Controllers
{
    public class MoviesController : OwnerController
    {
        private readonly IMoviesService _moviesService;
        private readonly ICinemasService _cinemasService;

        public MoviesController(IMoviesService moviesService, ICinemasService cinemasService)
        {
            _moviesService = moviesService;
            _cinemasService = cinemasService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _moviesService.GetFilterViewModelAsync());
        }
        public async Task<IActionResult> QueryMovies(string searchText, string filterValue, string sortBy, [ModelBinder(typeof(IntegerModelBinder))] int? pageNumber)
        {
            var movies = await _moviesService.QueryMoviesAsync(searchText, filterValue, sortBy, pageNumber ?? 1);
            return PartialView("_MoviesPartial", movies);
        }
        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            var viewModel = await _moviesService.GetDetailsViewModelAsync(id, User.Identity.Name);
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // GET: Movies/Create
        public async Task<IActionResult> Add()
        {
            return View(await _moviesService.GetCreateViewModelAsync());
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CreateMovieViewModel movieVM)
        {
            if (!movieVM.ActorsDropdown.Where(i => i.IsChecked).Any())
            {
                ModelState.AddModelError("ActorsDropdown", "Select at least 1 actor");
            }
            if (ModelState.IsValid)
            {
                await _moviesService.CreateMovieAsync(movieVM, User.Identity.Name);
                return RedirectToAction(nameof(Index));
            }
            return View(movieVM);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit([ModelBinder(typeof(IntegerModelBinder))] int id)
        {
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            var viewModel = await _moviesService.GetEditViewModelAsync(id);
            if (viewModel == null)
            {
                return NotFound();
            }

            return PartialView("_EditMoviePartial", viewModel);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] EditMovieViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _moviesService.EditMovieAsync(viewModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    bool movieExists = await _moviesService.ExistsByIdAsync(viewModel.Id);
                    if (!movieExists)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = viewModel.Id });
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete([ModelBinder(typeof(IntegerModelBinder))] int id)
        {
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }

            var viewModel = await _moviesService.GetDeleteViewModelAsync(id);
            return PartialView("_DeleteMoviePartial", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (!await _moviesService.ExistsByIdAsync(id))
            {
                return NotFound();
            }
            await _moviesService.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMovieToCinemas(MovieDetailsViewModel viewModel)
        {
            if (!await _moviesService.ExistsByIdAsync(viewModel.Id))
            {
                return NotFound();
            }
            await _moviesService.AddMovieToCinemasAsync(viewModel);
            return RedirectToAction(nameof(Details), new { id = viewModel.Id });
        }
        [HttpGet]
        public async Task<IActionResult> SetMovieSchedule(int? cinemaId, int? movieId)
        {
            if (!await _cinemasService.ExistsByIdAsync(cinemaId) || !await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }

            var viewModel = await _moviesService.GetSetMovieScheduleViewModelAsync(cinemaId, movieId);
            if (viewModel == null)
            {
                return NotFound();
            }
            return PartialView("_SetMovieSchedulePartial", viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> SetMovieSchedule(SetMovieScheduleViewModel viewModel)
        {
            if (!await _cinemasService.ExistsByIdAsync(viewModel.CinemaId) || !await _moviesService.ExistsByIdAsync(viewModel.MovieId))
            {
                return NotFound();
            }

            await _moviesService.SetMovieScheduleAsync(viewModel);
            return RedirectToAction(nameof(Details), new { id = viewModel.MovieId });
        }
        [HttpGet]
        public async Task<IActionResult> EditCinemaMovieData(int? cinemaId, int? movieId)
        {
            if (!await _cinemasService.ExistsByIdAsync(cinemaId) || !await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }

            var viewModel = await _moviesService.GetEditCinemaMovieDataViewModelAsync(cinemaId, movieId);
            if (viewModel == null)
            {
                return NotFound();
            }
            return PartialView("_EditCinemaMovieDataPartial", viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditCinemaMovieData(EditCinemaMovieDataViewModel viewModel)
        {
            if (!await _cinemasService.ExistsByIdAsync(viewModel.CinemaId) || !await _moviesService.ExistsByIdAsync(viewModel.MovieId))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _moviesService.EditCinemaMovieDataAsync(viewModel);
            }
            return RedirectToAction(nameof(Details), new { id = viewModel.MovieId });
        }
        public async Task<IActionResult> GetCinemasContainingMovie([ModelBinder(typeof(IntegerModelBinder))] int movieId, string sortBy, [ModelBinder(typeof(IntegerModelBinder))] int? pageNumber)
        {
            if (!await _moviesService.ExistsByIdAsync(movieId))
            {
                return NotFound();
            }
            var viewModel = await _cinemasService.QueryCinemasContainingMovieAsync(movieId, User.Identity.Name, sortBy, pageNumber);
            if (viewModel == null)
            {
                return NotFound();
            }
            return PartialView("_CinemasPartial", viewModel);
        }
    }
}

CinemaTic.Web/Areas/Admin/Views/Cinemas/Cinema.cshtml
@model CinemaTic.ViewModels.Admin.AdminCinemaDetailsViewModel
@{
    ViewData["Title"] = $"Cinema - {Model.Name}";
}

<link href="~/css/manage-dashboard.css" rel="stylesheet" />
<link rel="stylesheet" href="~/css/cards.css" />
<link href="~/css/modal.css" rel="stylesheet" />
<div class="app-content">
    <div class="app-content-header">
        <button class="mode-switch" title="Switch Theme">
            <svg class="moon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" width="24" height="24" viewBox="0 0 24 24">
                <defs></defs>
                <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"></path>
            </svg>
        </button>
    </div>
    <div class="products-area-wrapper gridView m-0 justify-content-center details">
        <div class="products-header">
            <div class="cinema-cell image">
                Cinema
                <button class="sort-button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 512 512"><path fill="currentColor" d="M287.1 347.2c-7.9-7.9-20.6-7.9-28.5 0l-85.7 85.7V80.1c0-11.3-9.1-20.4-20.4-20.4-11.3 0-20.4 9.1-20.4 20.4v352.8l-85.7-85.7c-7.9-7.9-20.6-7.9-28.5 0-7.9 7.9-7.9 20.6 0 28.5l120.4 120.4c7.9 7.9 20.6 7.9 28.5 0l120.4-120.4c7.8-7.9 7.8-20.7-.1-28.5z"></path><path fill="currentColor" d="M496.1 138.3L375.7 17.9c-7.9-7.9-20.6-7.9-28.5 0L226.9 138.3c-7.9 7.9-7.9 20.6 0 28.5 7.9 7.9 20.6 7.9 28.5 0l85.7-85.7v352.8c0 11.3 9.1 20.4 20.4 20.4 11.3 0 20.4-9.1 20.4-20.4V81.1l85.7 85.7c7.9 7.9 20.6 7.9 28.5 0 7.9-7.8 7.9-20.6 0-28.5z"></path></svg>
                </button>
            </div>
            <div class="cinema-cell description">
                Description<button class="sort-button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 512 512"><path fill="currentColor" d="M287.1 347.2c-7.9-7.9-20.6-7.9-28.5 0l-85.7 85.7V80.1c0-11.3-9.1-20.4-20.4-20.4-11.3 0-20.4 9.1-20.4 20.4v352.8l-85.7-85.7c-7.9-7.9-20.6-7.9-28.5 0-7.9 7.9-7.9 20.6 0 28.5l120.4 120.4c7.9 7.9 20.6 7.9 28.5 0l120.4-120.4c7.8-7.9 7.8-20.7-.1-28.5z"></path><path fill="currentColor" d="M496.1 138.3L375.7 17.9c-7.9-7.9-20.6-7.9-28.5 0L226.9 138.3c-7.9 7.9-7.9 20.6 0 28.5 7.9 7.9 20.6 7.9 28.5 0l85.7-85.7v352.8c0 11.3 9.1 20.4 20.4 20.4 11.3 0 20.4-9.1 20.4-20.4V81.1l85.7 85.7c7.9 7.9 20.6 7.9 28.5 0 7.9-7.8 7.9-20.6 0-28.5z"></path></svg>
                </button>
            </div>
            <div class="cinema-cell status-cell">
                Status<button class="sort-button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 512 512"><path fill="currentColor" d="M287.1 347.2c-7.9-7.9-20.6-7.9-28.5 0l-85.7 85.7V80.1c0-11.3-9.1-20.4-20.4-20.4-11.3 0-20.4 9.1-20.4 20.4v352.8l-85.7-85.7c-7.9-7.9-20.6-7.9-28.5 0-7.9 7.9-7.9 20.6 0 28.5l120.4 120.4c7.9 7.9 20.6 7.9 28.5 0l120.4-120.4c7.8-7.9 7.8-20.7-.1-28.5z"></path><path fill="currentColor" d="M496.1 138.3L375.7 17.9c-7.9-7.9-20.6-7.9-28.5 0L226.9 138.3c-7.9 7.9-7.9 20.6 0 28.5 7.9 7.9 20.6 7.9 28.5 0l85.7-85.7v352.8c0 11.3 9.1 20.4 20.4 20.4 11.3 0 20.4-9.1 20.4-20.4V81.1l85.7 85.7c7.9 7.9 20.6 7.9 28.5 0 7.9-7.8 7.9-20.6 0-28.5z"></path></svg>
                </button>
            </div>
            <div class="cinema-cell sales">
                Added on<button class="sort-button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 512 512"><path fill="currentColor" d="M287.1 347.2c-7.9-7.9-20.6-7.9-28.5 0l-85.7 85.7V80.1c0-11.3-9.1-20.4-20.4-20.4-11.3 0-20.4 9.1-20.4 20.4v352.8l-85.7-85.7c-7.9-7.9-20.6-7.9-28.5 0-7.9 7.9-7.9 20.6 0 28.5l120.4 120.4c7.9 7.9 20.6 7.9 28.5 0l120.4-120.4c7.8-7.9 7.8-20.7-.1-28.5z"></path><path fill="currentColor" d="M496.1 138.3L375.7 17.9c-7.9-7.9-20.6-7.9-28.5 0L226.9 138.3c-7.9 7.9-7.9 20.6 0 28.5 7.9 7.9 20.6 7.9 28.5 0l85.7-85.7v352.8c0 11.3 9.1 20.4 20.4 20.4 11.3 0 20.4-9.1 20.4-20.4V81.1l85.7 85.7c7.9 7.9 20.6 7.9 28.5 0 7.9-7.8 7.9-20.6 0-28.5z"></path></svg>
                </button>
            </div>
        </div>
        <div class="cinema-row details-card mb-3">
            <div class="cinema-cell image details-photo-pic">
                <a class="d-flex align-items-center cinema-link flex-column">
                    <img src="~/client-images/Cinemas/@Model.ImageUrl" alt="cinema-logo">
                    <span>@Model.Name</span>
                </a>
            </div>
            <div class="cinema-cell status-cell">
                <span class="cell-label">Status:</span>
                <span class="status">@Model.Status</span>
            </div>
            <div class="cinema-cell description">
                <span class="cell-label">Description:</span>
                <span class="cinema-description">
                    @Model.Description
                </span>
            </div>
            <div class="cinema-cell sales"><span class="cell-label">Founded on:</span>@Model.FoundedOn</div>
        </div>
        <div class="cinema-cell stock mb-3">
            <button id="change-status" class="action-button active crud-button open-popup-btn">Change approval status</button>
        </div>
    </div>
    <div class="products-area-wrapper movies-wrapper tableView">
        <div class="products-header">
            <div class="cinema-cell image">
                Movie
                <button class="sort-button" id="name-sort-desc" title="Sort descending">
                    <i class="fa-solid fa-arrow-down"></i>
                </button>
                <button class="sort-button" id="name-sort" title="Sort ascending">
                    <i class="fa-solid fa-arrow-up"></i>
                </button>
            </div>
            <div class="cinema-cell status-cell">
                Genre
                <button class="sort-button" id="genre-sort-desc" title="Sort descending">
                    <i class="fa-solid fa-arrow-down"></i>
                </button>
                <button class="sort-button" id="genre-sort" title="Sort ascending">
                    <i class="fa-solid fa-arrow-up"></i>
                </button>
            </div>
            <div class="cinema-cell sales">
                Average user rating
                <button class="sort-button" id="rating-sort-desc" title="Sort descending">
                    <i class="fa-solid fa-arrow-down"></i>
                </button>
                <button class="sort-button" id="rating-sort" title="Sort ascending">
                    <i class="fa-solid fa-arrow-up"></i>
                </button>
            </div>
            <div class="cinema-cell stock">
                Ratings count
                <button class="sort-button" id="ratingcount-sort-desc" title="Sort descending">
                    <i class="fa-solid fa-arrow-down"></i>
                </button>
                <button class="sort-button" id="ratingcount-sort" title="Sort ascending">
                    <i class="fa-solid fa-arrow-up"></i>
                </button>
            </div>
        </div>
        <div class="movies-container" id="results-container">
        </div>
    </div>
</div>
<partial name="_PopupModalPartial" />
<script>
    window.onload = function () {
        getItemCollectionByParent('Admin', 'Cinemas', 'QueryMoviesByCinema', '@Model.Id');
    };
    var modalContainer = document.getElementById('ud-form-container');
    var editButton = document.getElementById("change-status");

    var activeSort = document.querySelector('.sort-button.selected');
    document.querySelectorAll(".sort-button").forEach(i => i.addEventListener('click', function () {
        var alreadyActive = document.querySelector('.sort-button.selected');
        if (alreadyActive) {
            alreadyActive.classList.remove("selected");
        }
        i.classList.add("selected");
        activeSort = i;
        getItemCollectionByParent('Admin', 'Cinemas', 'QueryMoviesByCinema', '@Model.Id', null, null, activeSort.id);
    }));

    editButton.addEventListener("click", function () {
        modalContainer.innerHTML = "";
        getUDpartial('Admin', 'Cinemas', 'ChangeApprovalStatus', '@Model.Id');
    });
</script>
<script src="~/js/dashboard.js"></script>
<script src="~/js/modal.js"></script>

CinemaTic.Web/Areas/Admin/Views/Cinemas/_ChangeApprovalStatusPartial.cshtml
@model CinemaTic.ViewModels.Admin.ChangeCinemaApprovalStatusViewModel

<div class="delete-cinema-form d-flex justify-content-center align-items-center">
    <div class="delete-text d-flex flex-column">
        <h5>Are you sure you want to change this cinema's approval status?</h5>
        <form asp-area="Admin" asp-controller="Cinemas" asp-action="ChangeApprovalStatus" method="post" class="d-flex justify-content-evenly align-items-center">
            <div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <div class="active-form">
                        <i class="fa-solid fa-film input-icon"></i>
                        <span class="px-2">@Model.Name</span>
                    </div>
                </div>
                <select id="status-selector" class="status-selector" name="approvalCode" asp-for="ApprovalCode">
                    <option value="@((int)ApprovalStatus.Approved)">Approved</option>
                    <option value="@((int)ApprovalStatus.DeniedApproval)">Denied approval</option>
                </select>
                <button type="submit" class="app-content-headerButton bg-primary" asp-area="Admin" asp-controller="Cinemas" asp-action="ChangeApprovalStatus">Change</button>
            </div>

            <div class="delete-image form-group mx-0">
                <img src="~/client-images/Cinemas/@Model.ImageUrl" />
            </div>
        </form>
    </div>
</div>

CinemaTic.Web/Areas/Admin/Views/Cinemas/_CinemaMoviesPartial.cshtml
@model IEnumerable<CinemaTic.ViewModels.Movies.MovieInfoCardViewModel>

@foreach (var movie in Model)
{
    <div class="cinema-row">
        <button class="cell-more-button">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical"><circle cx="12" cy="12" r="1" /><circle cx="12" cy="5" r="1" /><circle cx="12" cy="19" r="1" /></svg>
        </button>
        <div class="cinema-cell image">
            <a class="d-flex align-items-center cinema-link" asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id">
                <img src="~/client-images/Movies/@movie.ImageUrl" alt="cinema-logo">
                <span>@movie.Name</span>
            </a>
        </div>
        <div class="cinema-cell sales"><span class="cell-label">Genre:</span>@movie.Genre</div>
        <div class="cinema-cell sales"><span class="cell-label">Average rating:</span>@movie.AverageRating / 10.0</div>
        <div class="cinema-cell stock"><span class="cell-label">Rating count:</span>@movie.RatingCount</div>
    </div>
    <div class="movie-grid" hidden>
        <div class="card-wrapper">
            <div class="card">
                <img src="~/client-images/Movies/@movie.ImageUrl" alt="cinema-logo">
                <div class="descriptions">
                    <div class="description-buttons">
                        <a class="desc-button" asp-controller="Movies" asp-action="Details" asp-route-id="@movie.Id">
                            <i class="fa-solid fa-circle-info f-size-b"></i>
                            Details
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

CinemaTic.Web/Areas/Admin/Views/Cinemas/_CinemasPartial.cshtml
@model PaginatedList<CinemaTic.ViewModels.Admin.AdminAllCinemasViewModel>

@foreach (var cinema in Model)
{
    <div class="cinema-row info-cinema">
        <button class="cell-more-button">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical"><circle cx="12" cy="12" r="1" /><circle cx="12" cy="5" r="1" /><circle cx="12" cy="19" r="1" /></svg>
        </button>
        <div class="cinema-cell image">
            <a class="d-flex align-items-center cinema-link" asp-area="Admin" asp-controller="Cinemas" asp-action="Cinema" asp-route-id="@cinema.Id">
                <img src="~/client-images/Cinemas/@cinema.ImageUrl" alt="cinema-logo">
                <span>@cinema.Name</span>
            </a>
        </div>
        <div class="cinema-cell status-cell">
            <span class="cell-label">Status:</span>
            <span class="status">@cinema.Status</span>
        </div>
        <div class="cinema-cell sales"><span class="cell-label">Added on:</span>@cinema.AddedOn</div>
        <div class="cinema-cell added-by">
            <span class="cell-label">Added by:</span>
            <a asp-area="Admin" asp-controller="Users" asp-action="User" asp-route-id="@cinema.AddedById">@cinema.AddedBy</a>
        </div>
    </div>
}
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
@if(Model.TotalPages > 1)
{
    <ul class="pagination gap-1">
        <li class="page-item">
            <a class="action-button active previous @prevDisabled">
                Previous
            </a>
        </li>
        <li class="page-item">
            <a class="action-button active next @nextDisabled">
                Next
            </a>
        </li>
    </ul>
}
<script>
    document.querySelectorAll('.page-item a').forEach(i => i.addEventListener("click", function () {
        if (i.classList.contains("previous")) {
            page = page - 1;
        }
        else if (i.classList.contains("next")) {
            page = page + 1;
        }
        getItems('Admin', 'Cinemas', 'QueryCinemas', page, search.value, (filterOptions ? filterOptions.value : null), (activeSort ? activeSort.id : null));
    }));
</script>